---
- name: Main | Configure | audispd-plugins | Getting Auditd version
  ansible.builtin.command: /sbin/auditctl -v
  register: auditd_installed_ver
  changed_when: false

- name: Main | Configure | audispd-plugins | Parsing Auditd major version
  ansible.builtin.set_fact:
    auditd_major_version: "{{ (auditd_installed_ver.stdout | regex_search('([0-9]+)') | default('0')) | int }}"

- name: Main | Configure | audispd-plugins | Modifying audispd-plugins config file (Auditd v2)
  when: auditd_major_version < 3
  ansible.builtin.lineinfile:
    path: "{{ audispd_plugin_config_v2 }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^active', line: 'active = yes' }
    - { regexp: '^args', line: 'args = LOG_LOCAL6' }

- name: Main | Configure | audispd-plugins | Modifying audispd-plugins config file (Auditd v3)
  when: auditd_major_version >= 3
  ansible.builtin.lineinfile:
    path: "{{ audispd_plugin_config_v3 }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^active', line: 'active = yes' }
    - { regexp: '^args', line: 'args = LOG_LOCAL6' }

- name: Main | Configure | audispd-plugins | Restarting Auditd service
  when: ansible_os_family != 'RedHat' and ansible_os_family != 'REDOS' and ansible_os_family != 'RED' and ansible_os_family != 'Altlinux'
  ansible.builtin.service:
    name: auditd
    state: restarted

- name: Main | Configure | audispd-plugins | Restarting Auditd service (RHEL-based)
  when: ansible_os_family == 'RedHat' or ansible_os_family == 'REDOS' or ansible_os_family == 'RED'
  ansible.builtin.service: name=auditd state=restarted use=service

- name: Main | Configure | audispd-plugins | Restarting Auditd service (Altlinux)
  when: ansible_os_family == 'Altlinux'
  ansible.builtin.command: 'service auditd restart'
